### USERS

# Testing the uptime of the users_route
curl -X GET \
  'http://localhost:3001/api/users/test'

# Adding a new user
curl -X POST \
  'http://localhost:3001/api/users/userDetails'
  -H 'Content-Type: application/json' \
  -d '{
    "name": "Sam H",
    "password": "test123+",
    "email": "sam@emailcom"
    '

# Getting the user-details
curl -X GET   \
  'http://localhost:3001/api/users/userDetails'
  -H 'Content-Type: application/json, api_key: <api-key>' \

# Updating the user-details
curl -X PATCH    \
  'http://localhost:3001/api/users/updateUser'
  -H 'Content-Type: application/json, api_key: <api-key>' \
  -d '{
    "password": "test1234+"
    '

# Refreshing the user-token
curl -X PATCH    \
  'http://localhost:3001/api/users/refreshToken'
  -H 'Content-Type: application/json, api_key: <api-key>' \

# Deleting the user
curl -X DELETE     \
  'http://localhost:3001/api/users/deleteUser'
  -H 'Content-Type: application/json, api_key: <api-key>' \


###############################################################################

### URLS

# Testing the uptime of the users_route
curl -X GET \
  'http://localhost:3001/api/urls/test'

# Generating a short_url
curl -X POST \
  'http://localhost:3001/api/urls/generate'
  -H 'Content-Type: application/json, api_key: <api-key>' \
  -d '{
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/F5_tornado_Elie_Manitoba_2007.jpg/1200px-F5_tornado_Elie_Manitoba_2007.jpg"
  }'

# Getting the url_data
curl -X GET \
  'http://localhost:3001/api/urls/tinyurl'
  -H 'Content-Type: application/json'\
  -d '{
    long_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/F5_tornado_Elie_Manitoba_2007.jpg/1200px-F5_tornado_Elie_Manitoba_2007.jpg"
  }'

# Deleting an url
curl -X DELETE  \
  'http://localhost:3001/api/urls/deleteUrl'
  -H 'Content-Type: application/json, api_key: <api-key>' \
  -d '{
    long_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/F5_tornado_Elie_Manitoba_2007.jpg/1200px-F5_tornado_Elie_Manitoba_2007.jpg"
  }'